#zuul注册到Eureka-service为服务后默认情况下是构建PAI-GATEWAY,只要在url这样拼接 zuul-host/appname/api
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: micoserice-gateway-zuul
server:
  port: 8090

# zuul 路由配置 方式一
#zuul:
#  routes:
#    micoserice-user: /user/**
  #忽略微服务,多个微服务用逗号隔开,忽略所有的服务时用'*'表示
#  ignored-services: micoserice-feign,micoserice-ribbon

#方式二，效果和方式一一样
#zuul:
#  routes:
#    user-routes: #user-routes只是一个路由名称可任意起名
#      service-id: micoserice-user
#      path: /user/** #service-id 对应路径
#  ignored-services: /**/admin/** #忽略所有包含/admin/的路径