#zuul注册到Eureka-service为服务后默认情况下是构建PAI-GATEWAY,只要在url这样拼接 zuul-host/appname/api
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: micoserice-gateway-zuul
server:
  port: 8090

# zuul 路由配置
zuul:
  routes:
    micoserice-user: /user/**
