
spring:
  application:
    name: micoserice-feign-customize
server:
   port: 8055
eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id:

