eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 9001
spring:
  application:
    name: microserice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoyangW/SpringCloud.git #git仓库地址
          search-paths: microserice-config #配置仓库路径
          username: username #git账户名
          password: password #git账户密码



