eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 9001
spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoyangW/SpringCloud/ #git仓库地址
          search-paths: microservice-config #配置仓库路径（目标文件路径）
          username: your name #git账户名
          password: your password #git账户密码



