server:
  port: 9001
spring:
  application:
    name: micoserice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoyangW/SpringCloud
          username: **** #git账户名
          password: **** #git账户密码


