server:
  port: 8761
eureka:
  client:
    service-url:
    defaultZone: http//admin:admin123@laclhost:8761/eureka
    register-with-eureka: false #把eureka-client禁用掉
    fetch-registry: false
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin123
